Traceback (most recent call last):
  File "c:\Users\chari\Documents\Python Programs\saveExceptionLog.py", line 7, in <module>
    raise Exception("This is the error message.")
Exception: This is the error message.
